name: Deploy to Heroku (Docker)

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Heroku Container Registry
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t registry.heroku.com/child-development-booklet/web -f backend/Dockerfile backend
          docker push registry.heroku.com/child-development-booklet/web

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t registry.heroku.com/child-development-booklet/frontend -f frontend/Dockerfile frontend
          docker push registry.heroku.com/child-development-booklet/frontend

      - name: Release the App
        run: |
          heroku container:release web frontend --app child-development-booklet
